blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Support
    url: https://github.com/pug523/shelf/discussions
    about: Please use GitHub Discussions for support, questions, or general help.
